## Site Configuration File ##
# name of the folder that the site will be generated in
name = "notion"

# the notion.so page to being parsing from. This page will become the index.html
# of the generated site, and loconotion will parse all sub-pages present on the page
page = "https://kira-network.notion.site/KIRA-Docs-1b60a7e5f21341ff8a1e4b2eeb2cc98e"

# optionally apply notion's dark mode, remove the line below to use the default light mode
# theme = "dark"

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Meta Tags ##
  # defined as an array of tables (double square brackets)
  # each key in the table maps to an atttribute in the tag
  # the following adds the tag <meta name="title" content="Loconotion Test Site"/>
  [[site.meta]]
  name = "docs"
  content = "KIRA | Docs"
  [[site.meta]]
  name = "description"
  content = "Public docs of the kira.network"
  [[site.inject.head.link]]
  rel="icon"
  sizes="192x192"
  type="image/png"
  href="https://ipfs.kira.network/ipfs/QmRqfyEvBoSj6sapjyhQqTJfwQPmsDkMQrxyqtTC6bZcTU"