name: Documentation Issue Report
description: Report an issue with the documentation
title: ""
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to report an issue with our documentation."
  - type: input
    id: page-found
    attributes:
      label: "Issue page path (local)"
      description: "The specific page local path where the issue was found. This field shouldn't be modified."
      placeholder: "e.g., /docs/introduction"
    validations:
      required: true
  - type: input
    id: build-found
    attributes:
      label: "Issue page path (docs.kira.network branch)"
      description: "The specific deployed page path where the issue was found. This field shouldn't be modified."
      placeholder: "e.g., /docs/introduction"
    validations:
      required: true
  - type: input
    id: kira-testnet-address
    attributes:
      label: "Your KIRA testnet address (optional)"
      description: "If you'd like, provide your KIRA testnet address. Who knows..."
      placeholder: "e.g., kira1..."
    validations:
      required: false
  - type: textarea
    id: issue-description
    attributes:
      label: "Description"
      description: "Please describe the issue succinctly."
      placeholder: "Detail the issue you've encountered..."
    validations:
      required: true