name: Ecosystem PR Workflow

on:
  pull_request:
    branches:
      - ecosystem

jobs:
  check_PR: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for details.json
        run: |
          if [ -f "details.json" ]; then
            echo "File 'details.json' found."
          else
            echo "Error: 'details.json' not found. Please include this file in your pull request."
            exit 1
          fi

  process_PR:  
    runs-on: ubuntu-latest
    needs: check_PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract project name from details.json
        run: |
          project_name=$(jq -r '.name' details.json)
          echo "::set-output name=project_name::$project_name"

      - name: Checkout repository to master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Create folder and move details.json
        run: |
          project_name=$(echo "${{ steps.extract_project_name.outputs.project_name }}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
          mkdir -p static/ecosystem/$project_name
          git show ${{ github.event.pull_request.head.ref }}:details.json > static/ecosystem/$project_name/details.json

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Add $project_name into ecosystem"
          commit-message: "Add details.json for $project_name into ecosystem"
          branch: master

      - name: Close initial PR
        run: gh pr close ${{ github.event.number }}

      - name: Delete inital branch
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}
