---
name: Ecosystem PR Workflow

on:
  pull_request:
    branches:
      - ecosystem

env:
  FILE: details.json

jobs:
  Check_PR_and_collect_the_file:
    runs-on: ubuntu-latest
    outputs:
      PROJECT_NAME: ${{ steps.extract_project_name.outputs.project_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ env.FILE }}
      - name: Extract project name from ${{ env.FILE }}
        id: extract_project_name
        run: |
          project_name=$(jq -r '.name' ${{ env.FILE }} | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
          echo "::set-output name=project_name::$project_name"
      - name: DEBUG Info
        run: |
          pwd
          ls -lah

      - name: Archive ${{ env.FILE }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}
          path: ${{ env.FILE }}
          if-no-file-found: error

  Create_PR_to_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Create folder and move ${{ env.FILE }}
        run: |
          mkdir -p ./ecosystem/submissions/${{ env.PROJECT_NAME }}
      - name: Downlowad archived file
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.FILE }}
      - name: DEBUG Info
        run: |
          pwd
          ls -lah

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: |
            "Add ${{ env.PROJECT_NAME }} into ecosystem"
          commit-message: |
            "Add ${{ env.FILE }} for ${{ env.PROJECT_NAME }} into ecosystem"
          branch: master

      - name: Close initial PR
        run: gh pr close ${{ github.event.number }}

      - name: Delete inital branch
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}
