name: Push Notion to IPFS

on:
  push:
    branches: [ master, dev ]

jobs:
 build:
    name: Repo Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: write
    container: 
      image: ghcr.io/kiracore/docker/base-image:v0.12.2
    steps:
      - name: Init
        run: |
          mkdir -p /github/home/.cache/pip
          git config --global --add safe.directory /github/home/.cache/pip
          git config --global --add safe.directory $PWD
          echo "INDEX_MODE=redirect" >> $GITHUB_ENV
          echo "SUBDOMAIN=docs" >> $GITHUB_ENV
          echo "DNS=kira.network" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "DISTRO=${GITHUB_WORKSPACE}/loconotion/dist/notion" >> $GITHUB_ENV
          echo "RELEASE=${GITHUB_WORKSPACE}/release" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Checkout loconotion
        uses: actions/checkout@v3
        with:
          repository: leoncvlt/loconotion
          ref: 759697ade3e29d97d5de477f8d39404e2c53789f
          path: loconotion
      - name: Download current version of the site
        uses: actions/checkout@v3
        with:
          repository: "KiraCore/${{env.SUBDOMAIN}}.${{env.DNS}}"
          ref: ${{ env.SOURCE_BRANCH }}
          path: _site
      - name: Install Loconotion & Build
        run: |
          cd ./loconotion
          pip install -r ./requirements.txt
          rm -rfv ./dist "${{env.DISTRO}}" "${{env.RELEASE}}"
          mkdir -p ./dist "${{env.DISTRO}}" "${{env.RELEASE}}"
          cp -fv ../_site/config.toml ./site.toml
          python loconotion "./site.toml" --chromedriver /usr/bin/chromedriver --timeout 600 
          echo "${{env.SOURCE_BRANCH}}" > "${{env.RELEASE}}/source.txt"
          echo "${{env.SUBDOMAIN}}.${{env.DNS}}" > "${{env.RELEASE}}/CNAME"
          cp -fv ../_site/LICENSE.md "${{env.RELEASE}}/LICENSE.md"
          cp -fv ../_site/${INDEX_MODE}.html "${{env.RELEASE}}/index.html"
          ls -a1 ../_site
          ls -a1 "${{env.DISTRO}}"
          ls -a1 "${{env.RELEASE}}"
      - name: Publish HTML to IPFS
        run: |
          set -x
          IPFS_UPLOAD_NAME="www-${{env.SUBDOMAIN}}.${{env.DNS}}-${{env.SOURCE_BRANCH}}"
          set -e
          ipfs-api delete $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true || echo "WARNING: Failed to delete file with name '$IPFS_UPLOAD_NAME' request failed or it might not exist"
          set +e
          ipfs-api pin "${{env.DISTRO}}" $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
          IPFS_HASH=$(cat ./ipfs-pin.log | tail -n 1 | bash-utils jsonParse ".hash" || echo "")
          [ -z "$IPFS_HASH" ] && echo "ERROR: IPFS Upload Failed" && exit 1
          echo "IPFS_HASH=$IPFS_HASH" >> $GITHUB_ENV
      - name: Save changes to release folder
        run: |
          ZIP_FILENAME="${{env.SUBDOMAIN}}.${{env.DNS}}.zip"
          cd "${{env.DISTRO}}"
          rm -fv "./$ZIP_FILENAME"
          zip -r "./$ZIP_FILENAME" ./*
          cp -fv "${{env.DISTRO}}/$ZIP_FILENAME" "${{env.RELEASE}}/$ZIP_FILENAME"

          echo "${{env.IPFS_HASH}}" > "${{env.DISTRO}}/ipfs-cid.txt"

          TARGET_VAR="IPFS_CID"
          REPLACE_VAR="https://ipfs.${{env.DNS}}/ipfs/${{env.IPFS_HASH}}"
          ESCAPED_VAR=$(echo "$REPLACE_VAR" | sed 's/\//\\\//g; s/&/\\&/g; s/\?/\\?/g')
          sed -i "s/$TARGET_VAR/$ESCAPED_VAR/g" "${{env.RELEASE}}/index.html"

          TARGET_VAR="GITHUB_REPO"
          REPLACE_VAR="https://github.com/KiraCore/${{env.SUBDOMAIN}}.${{env.DNS}}/tree/${{env.SOURCE_BRANCH}}-release"
          ESCAPED_VAR=$(echo "$REPLACE_VAR" | sed 's/\//\\\//g; s/&/\\&/g; s/\?/\\?/g')
          sed -i "s/$TARGET_VAR/$ESCAPED_VAR/g" "${{env.RELEASE}}/index.html"
      - name: Publish release folder
        uses: s0/git-publish-subdir-action@develop
        env:
            REPO: self
            BRANCH: "${{ env.SOURCE_BRANCH }}-release"
            FOLDER: "${{ env.RELEASE }}"
            GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
      - name: Cleanup
        run: |
          cd ${GITHUB_WORKSPACE}
          rm -rfv ./*
      - name: Download current version of the site
        if: env.SOURCE_BRANCH == 'dev'
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Create PR from dev to master branch
        uses: cea2aj/pull-request@84eb0c3478f13651e5649367941b867ca02d7926
        if: env.SOURCE_BRANCH == 'dev'
        with:
          github_token: ${{ secrets.REPO_ACCESS }}
          source_branch: ${{ env.SOURCE_BRANCH }}
          destination_branch: master
          pr_title: "${{ env.SOURCE_BRANCH }} -> master" 
          pr_label: "kira-automation"
          pr_allow_empty: true
          pr_body: |
             Web app was deployed to IPFS: ```${{env.IPFS_HASH}}```
             * Private Gateway: [ipfs.${{env.DNS}}/ipfs/${{env.IPFS_HASH}}](https://ipfs.${{env.DNS}}/ipfs/${{env.IPFS_HASH}}/index.html)
             * Public Gateway: [ipfs.io/ipfs/${{env.IPFS_HASH}}](https://ipfs.io/ipfs/${{env.IPFS_HASH}}/index.html)