name: Publish Notion website to GitHub Pages

on:
  # Manual update only.
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: igor-kupczynski/notion-exporter@c7457ff
        with:
          pages: "d8a73a70ab7544e29eb8638603ad9442"  # Pages IDs identified in (step 2)  
          output-dir: demo-docs
          notion-token: ${{ secrets.NOTION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}