name: Convert public notion page to HTML

on:
  # Manual update only.
  workflow_dispatch:

jobs:
 build:
    name: Repo Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: write
    container: 
      image: ghcr.io/kiracore/docker/base-image:v0.11.2
    steps:
      - name: Init
        run: |
          mkdir -p /github/home/.cache/pip
          git config --global --add safe.directory /github/workspace
          git config --global --add safe.directory /github/home/.cache/pip
          git config --global --add safe.directory $PWD
          echo "NOTION_PAGE_ID=d8a73a70ab7544e29eb8638603ad9442" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Checkout loconotion
        uses: actions/checkout@v3
        with:
          repository: leoncvlt/loconotion
          ref: 759697ade3e29d97d5de477f8d39404e2c53789f
          path: loconotion
      - name: Download current version of the site
        uses: actions/checkout@v3
        with:
          repository: 'KiraCore/docs.kira.network'
          ref: master
          path: _site
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Loconotion & Build
        run: |
          ls -a1 ./
          cd ./loconotion
          pip install -r ./requirements.txt
          rm -rfv ./dist ./src
          mkdir -p ./dist ./src
          cp -fv ../_site/config.toml ./site.toml
          python loconotion "./site.toml" --chromedriver /usr/bin/chromedriver
          cd ..
          cp -av ./_site/. ./
          cp -av "${GITHUB_WORKSPACE}/loconotion/dist/Demo Docs/." ./src
          rm -rf ./_site ./loconotion
          ls -a1 ./src
      - name: Publish HTML to IPFS
        run: |
          set -x
          IPFS_UPLOAD_NAME="www-docs-kira-network"
          set -e
          ipfs-api delete $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true || echo "WARNING: Failed to delete file with name '$IPFS_UPLOAD_NAME' request failed or it might not exist"
          set +e
          ipfs-api pin ./src $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
          IPFS_HASH=$(cat ./ipfs-pin.log | tail -n 1 | bash-utils jsonParse ".hash" || echo "")
          [ -z "$IPFS_HASH" ] && echo "ERROR: IPFS Upload Failed" && exit 1
          rm -fv ./ipfs-pin.log
          echo "$IPFS_HASH" > ./ipfs-cid.txt
          echo "IPFS_HASH=$IPFS_HASH" >> $GITHUB_ENV
          echo "IPFS_HASH_SHORT=$IPFS_HASH_SHORT" >> $GITHUB_ENV
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
          BRANCH: master
          COMMIT_MESSAGE: "Deployed to IPFS: ${{env.IPFS_HASH}}"

#    FOLDER: _site