name: Master PR Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  delete_ecosystem_branch:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'ecosystem')
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}