name: Deploy from Notion to Pages

on:
  # Manual update only.
  workflow_dispatch:

jobs:
 build:
    name: Repo Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: write
    container: 
      image: ghcr.io/kiracore/docker/base-image:v0.11.2
    steps:
      - name: Add safe.directory
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global --add safe.directory $PWD
      - name: Submodule Update
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          sudo apt-get update

      - name: Download notion4ever
        uses: actions/checkout@v2
        with:
          repository: 'MerkulovDaniil/notion4ever'
          
      - name: Install packages
        run: |
             NOTION_PAGE_ID="d8a73a70ab7544e29eb8638603ad9442"
             echo "NOTION_PAGE_ID=$NOTION_PAGE_ID" >> $GITHUB_ENV
             chmod -R 777 /github/home/.cache/pip
             echo "NOTION_PAGE_ID: $NOTION_PAGE_ID"
             pip install -r requirements.txt
      - name: Download current version of the site
        uses: actions/checkout@v2
        with:
          # HERE, YOU NEED TO PLACE YOUR REPOSITORY
          repository: 'KiraCore/docs.kira.network'
          # TARGET BRANCH
          ref: master
          # THE FOLDER, WHERE NOTION4EVER EXPORTS YOUR CONTENT BY DEFAULT
          path: _site
          
      - name: Run notion4ever
        run: python -m notion4ever
        env:
            # HERE YOU NEED TO PLACE URL OF THE ROOT PAGE. PROBABLY IT IS "https://<username>.github.io"
            SITE_URL: "https://test-docs.kira.network"
            NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
            NOTION_PAGE_ID: ${{env.NOTION_PAGE_ID}}
      
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
          BRANCH: master
          FOLDER: _site
          COMMIT_MESSAGE: 🤖 Notion page deployed.